# Generated by Django 3.0.6 on 2020-05-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_playingtime', models.IntegerField(max_length=2, verbose_name='오늘 공부랑')),
                ('today_messingtime', models.IntegerField(max_length=2, verbose_name='오늘 딴짓량')),
                ('eating_time', models.IntegerField(default=2, max_length=2, verbose_name='밥먹은시간')),
                ('other_time', models.IntegerField(default=2, max_length=2, verbose_name='기타 딴짓 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
