# Generated by Django 3.0.6 on 2020-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messingdata',
            name='sleeping_time',
            field=models.IntegerField(default=8, verbose_name='잠든 시간'),
        ),
        migrations.AlterField(
            model_name='messingdata',
            name='eating_time',
            field=models.IntegerField(default=2, verbose_name='밥 먹은 시간'),
        ),
        migrations.AlterField(
            model_name='messingdata',
            name='other_time',
            field=models.IntegerField(default=0, verbose_name='기타 딴짓 시간'),
        ),
        migrations.AlterField(
            model_name='messingdata',
            name='today_messingtime',
            field=models.IntegerField(verbose_name='오늘 딴짓량'),
        ),
        migrations.AlterField(
            model_name='messingdata',
            name='today_playingtime',
            field=models.IntegerField(verbose_name='오늘 공부랑'),
        ),
    ]
